// {{ autogenerated_disclaimer }}
#include <{{ header }}>

{{ class_name }}::{{ class_name }}(QObject* parent)
    : QObject(parent) {
}

{% for property in properties %}
{{ property.type }} {{ class_name }}::{{ property.name }}() const {
    return {{ property.var_name }};
}

{%- if property.mutability == 'readwrite' %}
void {{ class_name }}::{{ property.setter_name }}({{ property.arg_type }} value) {
    {% if property.type == 'qreal' %}
    if (qFuzzyCompare({{ property.var_name }}, value)) {
    {% else %}
    if ({{ property.var_name }} == value) {
    {% endif %}
        return;
    }
    {{ property.var_name }} = value;
    {{ property.name }}Changed(value);
}
{%- endif %}
{% endfor %}
